name: dev-environment
services:
  api:
    image: mcr.microsoft.com/dotnet/sdk:9.0 
    container_name: api-backend
    volumes:
      - /home/gbad8/Work/tries/trilha-net-fundamentos-desafio:/app
    working_dir: /app/Backend
    ports:
      - 8000:8080
    command: dotnet run
    networks:
      - backend

  blazor:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: blazor-frontend
    volumes:
      - /home/gbad8/Work/tries/trilha-net-fundamentos-desafio:/app
    working_dir: /app/Frontend
    ports:
      - 5001:8080
    command: dotnet run
    networks:
     - backend

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Df1516170224*
      - MSSQL_PID=Express
    hostname: "db"
    ports:
      - 1433:1433
    volumes:
      - mssql-volume:/var/opt/mssql
    networks:
      - backend

networks:
  backend:

volumes:
  mssql-volume:
