name: dev-environment
services:
  pde:
    build: ./arch
    tty: true
    volumes:
      - ~/Work:/home/gbad8/Work
    ports:
      - 8000:8080
    networks:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Df1516170224*
      - MSSQL_PID=Express
    hostname: "db"
    ports:
      - 1433:1433
    volumes:
      - mssql-volume:/var/opt/mssql
    networks:
      - backend

networks:
  backend:

volumes:
  mssql-volume:
